development:
  admin:
  - admin@admin.com
  archivist:
    - archivist1@example.com
    - admin@admin.com

test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:git p
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  admin:
    - admin@example.com
    - admin@admin.com
